DROP TABLE IF EXISTS article;

CREATE TABLE article (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  url VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  rating VARCHAR(255) NOT NULL,
  content CLOB NOT NULL
);